[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    ottowinter/ESPAsyncWebServer-esphome
    esphome/AsyncTCP-esphome

board_build.filesystem = littlefs 